apiVersion: v1
kind: ConfigMap
metadata:
  name: cart-service-config
  namespace: cloudshelf
data:
  SERVER_PORT: "8087"
  SPRING_APPLICATION_NAME: "cart-service"
  SPRING_REDIS_HOST: "redis"
  SPRING_REDIS_PORT: "6379"
  STOCK_CHECK_SERVICE_URL: "http://stock-check-service.cloudshelf.svc.cluster.local:8083"
  ORDER_SERVICE_URL: "http://order-service.cloudshelf.svc.cluster.local:8082"
  MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: "http://zipkin.cloudshelf.svc.cluster.local:9411/api/v2/spans"
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "health,info,prometheus,metrics"