apiVersion: v1
kind: ConfigMap
metadata:
  name: order-service-config
  namespace: cloudshelf
data:
  SERVER_PORT: "8082"
  SPRING_APPLICATION_NAME: "order-service"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres-order.cloudshelf.svc.cluster.local:5432/order_service"
  SPRING_KAFKA_BOOTSTRAP_SERVERS: "kafka.cloudshelf.svc.cluster.local:9092"
  STOCK_CHECK_SERVICE_URL: "http://stock-check-service.cloudshelf.svc.cluster.local:8083"
  MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: "http://zipkin.cloudshelf.svc.cluster.local:9411/api/v2/spans"
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "health,info,prometheus,metrics"
