apiVersion: v1
kind: ConfigMap
metadata:
  name: reviews-service-config
  namespace: cloudshelf
data:
  SERVER_PORT: "8086"
  SPRING_APPLICATION_NAME: "reviews-service"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
  SPRING_JPA_SHOW_SQL: "false"
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "health,info,prometheus,metrics"
  MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS: "always"