apiVersion: v1
kind: ServiceAccount
metadata:
  name: message-service-sa
  namespace: cloudshelf
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::443071119316:role/cloudshelf-message-service-sns-role