apiVersion: v1
kind: Secret
metadata:
  name: database-secrets
  namespace: cloudshelf
type: Opaque
stringData:
  POSTGRES_USER: "admin"
  POSTGRES_PASSWORD: "cloudshelf2025"
  MONGO_INITDB_ROOT_USERNAME: "admin"
  MONGO_INITDB_ROOT_PASSWORD: "cloudshelf2025"
  SPRING_DATASOURCE_USERNAME: "admin"
  SPRING_DATASOURCE_PASSWORD: "cloudshelf2025"
  SPRING_R2DBC_USERNAME: "admin"
  SPRING_R2DBC_PASSWORD: "cloudshelf2025"
  SPRING_DATA_MONGODB_USERNAME: "admin"
  SPRING_DATA_MONGODB_PASSWORD: "cloudshelf2025"
  SPRING_FLYWAY_USER: "admin"
  SPRING_FLYWAY_PASSWORD: "cloudshelf2025"
