server:
  port: 8081

spring:
  application:
    name: book-service
  
  data:
    mongodb:
      host: ${SPRING_DATA_MONGODB_HOST:mongo}
      port: ${SPRING_DATA_MONGODB_PORT:27017}
      database: ${SPRING_DATA_MONGODB_DATABASE:book-service}
      authentication-database: admin
      username: ${SPRING_DATA_MONGODB_USERNAME:admin}
      password: ${SPRING_DATA_MONGODB_PASSWORD:password}

management:
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans