server:
  port: 8083

spring:
  application:
    name: stock-check-service
  
  datasource:
    url: jdbc:postgresql://postgres-stock:5432/stock_check_service
    username: ${SPRING_DATASOURCE_USERNAME:admin}
    password: ${SPRING_DATASOURCE_PASSWORD:password}

management:
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans